name = "Wcs_hugo_theme"
description = ""
homepage = "https://blog.wonmocyberschool.com/"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = ""
  homepage = ""

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
